server:
  port: 8082

spring:
  application:
    name: vehicle-platform

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/vehicle_platform_db}

vehicle-sale-service:
  base-url: ${VEHICLE_SALE_SERVICE_URL:http://localhost:8080}
  timeout: ${VEHICLE_SALE_SERVICE_TIMEOUT:5000}