apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vehicle-platform-mongodb-pvc
  namespace: vehicle-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi