apiVersion: v1
kind: Service
metadata:
  name: vehicle-platform-mongodb
  namespace: vehicle-system
spec:
  type: ClusterIP
  selector:
    app: vehicle-platform-mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017